### ISSUE TITLE
Create action 

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/action-forc#1]
Ref https://github.com/FuelLabs/action-fuel-toolchain and https://github.com/actions-rs/cargo

We want an action like the `cargo` action above that allows users to run `forc` after it's been installed with the `fuel-toolchain` action above. So something like

```yaml
on: [push]

name: CI

jobs:
  build_and_test:
    name: Sway project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.1.0
      - name: Run forc build           # <--- step is what this issue is for
        uses: FuelLabs/action-forc@v1
        with:
          command: build
```
